## Analyzing football success: Unveiling key stats that make teams thrive

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup, Comment
import numpy as np
import html5lib

def download_table(url, filename):
    
    response = requests.get(url, timeout= 50)
    
    if response.status_code == 200:
        
        soup = BeautifulSoup(response.text, "html.parser")
        #Find the table that is commented out
        comments = soup.find_all(string=lambda text: isinstance(text, Comment))

        tables = []
        for each_line in comments:
            if 'table' in each_line:
                try:
                    #use extend instead of list.append so we don't have a 2d dataframe
                    tables.extend(pd.read_html(each_line))
                except:
                    continue

        df = pd.concat(tables, ignore_index = True)
        df.to_csv(f'{filename}.csv', index=False)
        print(f'Successfully created {filename}.csv')
    else:
        print(f'{response.status_code}: Error connecting to site')

download_table('https://fbref.com/en/comps/9/2022-2023/keepers/2022-2023-Premier-League-Stats', 'Player_goalkeeping')
download_table('https://fbref.com/en/comps/9/2022-2023/defense/2022-2023-Premier-League-Stats', 'Player_defense')
download_table('https://fbref.com/en/comps/9/2022-2023/passing/2022-2023-Premier-League-Stats', 'Player_passing')
download_table('https://fbref.com/en/comps/9/2022-2023/stats/2022-2023-Premier-League-Stats', 'Player_stats')

Successfully created Player_info.csv

In [ ]:
df = pd.read_csv('Player_passing.csv', skiprows = 1)
df_selected = df.iloc[:, 2:]
df_selected
pd.set_option('display.max_columns', 30)
df

,Unnamed: 0,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Cmp,Att,Cmp%,TotDist,PrgDist,Cmp.1,...,Att.2,Cmp%.2,Cmp.3,Att.3,Cmp%.3,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
0,0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,21,2000,26.4,592,797,74.3,7577,2182,346,...,195,76.9,25,65,38.5,3,4.2,2.6,-1.2,46,47,16,4,86,Matches
1,1,2,George Abbott,eng ENG,MF,Tottenham,16,2005,0.0,1,1,100.0,8,0,1,...,0,NaN,0,0,NaN,0,0.0,0.0,0.0,0,0,0,0,0,Matches
2,2,3,Che Adams,sct SCO,FW,Southampton,26,1996,22.1,330,498,66.3,4651,1042,205,...,118,66.1,26,37,70.3,3,2.8,2.2,+0.2,24,21,11,2,34,Matches
3,3,4,Tyler Adams,us USA,MF,Leeds United,23,1999,24.0,1108,1343,82.5,16592,5061,607,...,460,84.8,63,107,58.9,0,1.4,1.0,-1.4,24,110,13,0,136,Matches
4,4,5,Tosin Adarabioyo,eng ENG,DF,Fulham,24,1997,23.2,1066,1300,82.0,22623,8478,265,...,735,88.8,136,223,61.0,0,0.4,0.5,-0.4,6,96,7,0,95,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,586,565,Jordan Zemura,zw ZIM,DF,Bournemouth,22,1999,16.2,423,594,71.2,6117,3247,242,...,187,71.1,23,55,41.8,1,1.9,2.1,-0.9,18,32,12,5,45,Matches
587,587,566,Oleksandr Zinchenko,ua UKR,DF,Arsenal,25,1996,23.5,1652,1911,86.4,27023,7899,808,...,798,87.2,105,148,70.9,2,1.4,2.4,+0.6,19,201,41,4,227,Matches
588,588,567,Hakim Ziyech,ma MAR,"FW,MF",Chelsea,29,1993,7.3,258,400,64.5,4222,1570,148,...,133,61.7,24,66,36.4,3,2.2,1.5,+0.8,14,20,19,7,42,Matches
589,589,568,Kurt Zouma,fr FRA,DF,West Ham,27,1994,22.1,701,831,84.4,13480,4437,247,...,407,89.2,79,129,61.2,0,0.1,0.1,-0.1,1,19,2,0,31,Matches
590,590,569,Martin Ødegaard,no NOR,MF,Arsenal,23,1998,34.7,1449,1804,80.3,22540,6014,759,...,617,84.0,110,175,62.9,7,8.1,7.9,-1.1,76,135,91,4,266,Matches

In [ ]:
url = "https://sofascores.p.rapidapi.com/v1/seasons/standings"
querystring = {"seasons_id": "41886", "standing_type": "total", "unique_tournament_id": "17"}

headers = {
    "X-RapidAPI-Key": "723fee1b48msh84c111594949e90p1fe36djsn9c02ea5b5402",
    "X-RapidAPI-Host": "sofascores.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()

# Extracting the relevant data
rows = data['data'][0]['rows']

# Creating a DataFrame
df = pd.DataFrame(rows)

# Extracting specific columns
columns_to_extract = ['name', 'position', 'matches', 'wins', 'scoresFor', 'scoresAgainst', 'losses', 'draws', 'points']
df_result = df[['team', 'position', 'matches', 'wins', 'scoresFor', 'scoresAgainst', 'losses', 'draws', 'points']].copy()

# Extracting values from nested dictionaries within the 'team' column
df_result['name'] = df_result['team'].str.get('name')

# Dropping the 'team' column
df_result.drop('team', axis=1, inplace=True)

# Reordering columns
df_result = df_result[['name', 'position', 'matches', 'wins', 'scoresFor', 'scoresAgainst', 'losses', 'draws', 'points']]

#expand the display so all columns fit on the same page
pd.set_option('display.expand_frame_repr', None)
# Displaying the result
df_result